import type { Metadata } from "next";
import Header from "@/app/_components/layouts/Header";
import Footer from "@/app/_components/layouts/Footer";
import "destyle.css";
import { Inter } from "next/font/google";
import "@/app/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "デザインの部屋 | デザインの総合メディア",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="container">
          <Header />
          { children }
          <Footer />
        </div>
      </body>
    </html>
  );
}
