import type { Metadata } from "next";
import Header from "@/app/_components/layouts/Header";
import Footer from "@/app/_components/layouts/Footer";
import "destyle.css";
import  {Zen_Kaku_Gothic_New } from 'next/font/google'
import "@/app/styles/global.scss";

const ZenKakuGothicNew = Zen_Kaku_Gothic_New({
  weight: ["400", "700"],
  display: "swap",
  preload: false,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "デザインの部屋 | デザインの総合メディア",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={ZenKakuGothicNew.className}>
        <div className="container">
          <Header />
          <main>
          { children }
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
